version: "3"

services:
  rides:
    image: rides:latest
    build: ./rides
    command: gunicorn rides_app:app -w 1 -b 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    container_name: rides
    environment:
      - TEAM_NAME=CC_0075_1359_1532_1549

  users:
    image: users:latest
    build: ./users
    command: gunicorn users_app:app -w 1 -b 0.0.0.0:8080
    restart: always
    ports:
      - "8080:8080"
    container_name: users
    environment:
      - TEAM_NAME=CC_0075_1359_1532_1549
  
  orchestrator:
    container_name: orchestrator
    build: ./orch
    image: orchestrator
    depends_on:
      - rabbitmq
    command: sh -c "sleep 30 && python -u orch.py"
    restart: always
    ports:
      - "80:80"
    environment:
      - TEAM_NAME=CC_0075_1359_1532_1549

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq
    ports:
      - "5672:5672"
  
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper
    ports:
      - "2181:2181"

